"""initial schema

Revision ID: 7154121c2d9b
Revises: 
Create Date: 2026-08-06 12:08:54.603010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7154121c2d9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='卫星名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='卫星代号'),
    sa.Column('orbit_type', sa.String(length=64), nullable=False, comment='轨道类型'),
    sa.Column('launch_date', sa.Date(), nullable=True, comment='发射日期'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False, comment='1=在轨/AIT 2=停用'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellites_code'), 'satellites', ['code'], unique=True)
    op.create_table('telemetry_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False, comment='时间戳'),
    sa.Column('satellite_id', sa.Integer(), nullable=False, comment='冗余卫星ID，便于按库聚合'),
    sa.Column('channel_id', sa.Integer(), nullable=False, comment='接收通道ID'),
    sa.Column('param_code', sa.String(length=32), nullable=False, comment='参数代号'),
    sa.Column('raw_value', sa.BigInteger(), nullable=False, comment='源码整型值'),
    sa.Column('value', sa.Float(), nullable=False, comment='工程值'),
    sa.Column('quality', sa.Enum('GOOD', 'BAD', 'SUSPECT'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_param_ts', 'telemetry_data', ['param_code', 'ts'], unique=False)
    op.create_index('idx_ts_param', 'telemetry_data', ['ts', 'param_code'], unique=False)
    op.create_index(op.f('ix_telemetry_data_satellite_id'), 'telemetry_data', ['satellite_id'], unique=False)
    op.create_index(op.f('ix_telemetry_data_ts'), 'telemetry_data', ['ts'], unique=False)
    op.create_table('telemetry_frames',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('protocol_type', sa.String(length=32), nullable=False),
    sa.Column('apid', sa.Integer(), nullable=False, comment='CCSDS APID，其它协议为0'),
    sa.Column('raw_hex', sa.Text(), nullable=False, comment='整帧十六进制字符串'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_frame_ts', 'telemetry_frames', ['ts'], unique=False)
    op.create_index(op.f('ix_telemetry_frames_satellite_id'), 'telemetry_frames', ['satellite_id'], unique=False)
    op.create_index(op.f('ix_telemetry_frames_ts'), 'telemetry_frames', ['ts'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'observer'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False, comment='通道名称'),
    sa.Column('protocol_type', sa.Enum('CCSDS', '1553B', 'CAN', 'RS422'), nullable=False, comment='协议类型'),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('baud_rate', sa.Integer(), nullable=False, comment='波特率(串口)'),
    sa.Column('frame_format', sa.String(length=64), nullable=True, comment='帧格式描述'),
    sa.Column('running', sa.Integer(), nullable=False, comment='1=接收中 0=停止'),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_satellite_id'), 'channels', ['satellite_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True, comment='冗余用户名'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='操作动作'),
    sa.Column('target', sa.String(length=128), nullable=True, comment='操作对象'),
    sa.Column('detail', sa.Text(), nullable=True, comment='详情(JSON)'),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_table('telemetry_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('param_code', sa.String(length=32), nullable=False, comment='参数代号'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='参数名称'),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('subsystem', sa.String(length=64), nullable=False, comment='所属分系统，用于参数树：姿态控制/电源/热控等'),
    sa.Column('data_type', sa.String(length=32), nullable=False, comment='数据类型: uint8/int16/float/string/enum'),
    sa.Column('unit', sa.String(length=32), nullable=False, comment='工程单位'),
    sa.Column('formula', sa.String(length=255), nullable=True, comment='转换公式(源码→工程值)'),
    sa.Column('raw_bits', sa.Integer(), nullable=False, comment='源码位宽'),
    sa.Column('scale', sa.Float(), nullable=False, comment='线性系数'),
    sa.Column('offset', sa.Float(), nullable=False, comment='线性偏移'),
    sa.Column('precision', sa.Integer(), nullable=False, comment='工程值小数位'),
    sa.Column('threshold_min', sa.Float(), nullable=True, comment='告警下限'),
    sa.Column('threshold_max', sa.Float(), nullable=True, comment='告警上限'),
    sa.Column('enabled', sa.Integer(), nullable=False, comment='1=启用 0=停用'),
    sa.Column('order_no', sa.Integer(), nullable=False, comment='显示排序'),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id', 'param_code', name='uk_sat_param')
    )
    op.create_index(op.f('ix_telemetry_params_param_code'), 'telemetry_params', ['param_code'], unique=False)
    op.create_index(op.f('ix_telemetry_params_satellite_id'), 'telemetry_params', ['satellite_id'], unique=False)
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('param_id', sa.Integer(), nullable=False),
    sa.Column('alarm_type', sa.String(length=32), nullable=False, comment='告警类型'),
    sa.Column('threshold', sa.Float(), nullable=True, comment='触发阈值'),
    sa.Column('actual_value', sa.Float(), nullable=False, comment='实际值'),
    sa.Column('level', sa.String(length=16), nullable=False, comment='级别: INFO/WARN/CRITICAL'),
    sa.Column('status', sa.Integer(), nullable=False, comment='0=未处理 1=已处理'),
    sa.Column('message', sa.String(length=255), nullable=True, comment='告警说明'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('handled_by', sa.Integer(), nullable=True, comment='处理人ID'),
    sa.Column('handle_note', sa.String(length=255), nullable=True, comment='处理备注'),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['param_id'], ['telemetry_params.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_created_at'), 'alarms', ['created_at'], unique=False)
    op.create_index(op.f('ix_alarms_param_id'), 'alarms', ['param_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alarms_param_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_created_at'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_telemetry_params_satellite_id'), table_name='telemetry_params')
    op.drop_index(op.f('ix_telemetry_params_param_code'), table_name='telemetry_params')
    op.drop_table('telemetry_params')
    op.drop_index(op.f('ix_operation_logs_user_id'), table_name='operation_logs')
    op.drop_index(op.f('ix_operation_logs_created_at'), table_name='operation_logs')
    op.drop_table('operation_logs')
    op.drop_index(op.f('ix_channels_satellite_id'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telemetry_frames_ts'), table_name='telemetry_frames')
    op.drop_index(op.f('ix_telemetry_frames_satellite_id'), table_name='telemetry_frames')
    op.drop_index('idx_frame_ts', table_name='telemetry_frames')
    op.drop_table('telemetry_frames')
    op.drop_index(op.f('ix_telemetry_data_ts'), table_name='telemetry_data')
    op.drop_index(op.f('ix_telemetry_data_satellite_id'), table_name='telemetry_data')
    op.drop_index('idx_ts_param', table_name='telemetry_data')
    op.drop_index('idx_param_ts', table_name='telemetry_data')
    op.drop_table('telemetry_data')
    op.drop_index(op.f('ix_satellites_code'), table_name='satellites')
    op.drop_table('satellites')
    # ### end Alembic commands ###
